language: R

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_bioc SummarizedExperiment
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_r covr

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  global:
    - BIOC_USE_DEVEL="FALSE"

after_success:
  - Rscript -e 'library(covr); codecov()'
