language: R
sudo: required
cache: packages

before_install:
- chmod +x travis_setup.sh
- "./travis_setup.sh"
r:
- devtools
- bioc-devel
- bioc-release
- RColorBrewer
- doMC
- glmnet
- pheatmap
- ranger
- viridislite
- ggplot2
- covr

bioc:
- SummarizedExperiment

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  global:
  - BIOC_USE_DEVEL="FALSE"
  - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
  - HDF5_VERSION=1.8.13
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

notifications:
  slack: kelvinucam:typ0E36xGGP4DSkBOJEUnnv5

after_success:
  - Rscript -e 'library(covr); codecov()'
