language: R
sudo: required
cache: packages

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh

install:
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_bioc SummarizedExperiment
  - ./travis-tool.sh install_r RColorBrewer
  - ./travis-tool.sh install_r doMC
  - ./travis-tool.sh install_r glmnet
  - ./travis-tool.sh install_r pheatmap
  - ./travis-tool.sh install_r ranger
  - ./travis-tool.sh install_r viridislite
  - ./travis-tool.sh install_r ggplot2
  - ./travis-tool.sh install_r covr

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  global:
  - BIOC_USE_DEVEL="FALSE"
  - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
  - HDF5_VERSION=1.8.13
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

notifications:
  slack: kelvinucam:typ0E36xGGP4DSkBOJEUnnv5

after_success:
  - Rscript -e 'library(covr); codecov()'
